server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true

camunda:
  bpm:
    database:
      type: h2
      schema-update: true
    admin-user:
      id: demo
      password: demo
    filter:
      create: All tasks
    deployment-resource-pattern:
      - classpath*:processes/*.bpmn
      - classpath*:forms/*.form
